# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        test-and-coverage:
            environment:
                php:
                    version: 8.0.2
                    ini:
                        'xdebug.mode': 'coverage'
            tests:
                override:
                    -   command: 'vendor/bin/phpunit --coverage-clover=code-coverage'
                        coverage:
                            file: 'code-coverage'
                            format: 'clover'
