# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        test-and-coverage:
            environment:
                php:
                    version: 7.4.0
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=some-file'
                        coverage:
                            file: 'some-file'
                            format: 'clover'
